# Generated by Django 6.0.1 on 2026-01-15 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_extra_data_message_message_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='message',
            name='message_type',
        ),
    ]
